name: Docker Image CI

on: [push]

jobs:

build:

runs-on: ubuntu-latest

steps:
- uses: actions/checkout@v2
- name: Build the docker-compose stack
run: docker-compose up -d
- name: Sleep
- name: Check running containers
run: docker ps
- name: Run test suite
run: docker exec backend pytest --skip-auth
